# Generated by Django 3.2.9 on 2021-12-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_excercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='excercise',
        ),
    ]
