# Generated by Django 3.2.9 on 2021-12-03 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workoutinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('setnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbellrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbellrows', to='contents.workoutinfo')),
                ('benchpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchpresss', to='contents.workoutinfo')),
                ('cablepulldown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cablepulldowns', to='contents.workoutinfo')),
                ('cablepushdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cablepushdowns', to='contents.workoutinfo')),
                ('chestpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chestpresss', to='contents.workoutinfo')),
                ('deadlift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlifts', to='contents.workoutinfo')),
                ('dips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipss', to='contents.workoutinfo')),
                ('dumbellbenchpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumbellbenchpresss', to='contents.workoutinfo')),
                ('dumbellrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumbellrows', to='contents.workoutinfo')),
                ('dumbellshoulderpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumbellshoulderpresss', to='contents.workoutinfo')),
                ('frontraise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontraises', to='contents.workoutinfo')),
                ('inclinebenchpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclinebenchpresss', to='contents.workoutinfo')),
                ('innerthigh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innerthighs', to='contents.workoutinfo')),
                ('lateralpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateralpresss', to='contents.workoutinfo')),
                ('legcurl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legcurls', to='contents.workoutinfo')),
                ('legextension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legextensions', to='contents.workoutinfo')),
                ('legpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legpresss', to='contents.workoutinfo')),
                ('letpulldown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letpulldowns', to='contents.workoutinfo')),
                ('lunge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunges', to='contents.workoutinfo')),
                ('militarypress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militarypresss', to='contents.workoutinfo')),
                ('overheadpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheadpresss', to='contents.workoutinfo')),
                ('pullup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pullups', to='contents.workoutinfo')),
                ('seatedrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatedrows', to='contents.workoutinfo')),
                ('shoulderpress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoulderpresss', to='contents.workoutinfo')),
                ('squat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squats', to='contents.workoutinfo')),
            ],
        ),
    ]
