# Generated by Django 3.2.9 on 2021-12-10 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='barbellrow',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='benchpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='cablepulldown',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='cablepushdown',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='chestpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='deadlift',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='dips',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='dumbellbenchpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='dumbellrow',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='dumbellshoulderpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='frontraise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='inclinebenchpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='innerthigh',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='lateralpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='legcurl',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='legextension',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='legpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='letpulldown',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='lunge',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='militarypress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='overheadpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='pullup',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='seatedrow',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='shoulderpress',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='squat',
        ),
        migrations.RemoveField(
            model_name='workoutinfo',
            name='setnum',
        ),
        migrations.RemoveField(
            model_name='workoutinfo',
            name='weight',
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL),
        ),
    ]
