# Generated by Django 3.2.9 on 2021-12-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20211211_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
