# Generated by Django 3.2.9 on 2021-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20211216_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='set',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
