# Generated by Django 3.2.9 on 2021-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_workout_setls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='setls',
            new_name='settotal',
        ),
        migrations.AddField(
            model_name='workout',
            name='timetotal',
            field=models.TextField(null=True),
        ),
    ]
