# Generated by Django 3.2.9 on 2021-12-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20211216_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='set',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='settotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='timetotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workoutlist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
