# Generated by Django 3.2.9 on 2021-12-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20211216_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='set',
            new_name='se',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='time',
            new_name='tim',
        ),
    ]
