# Generated by Django 3.2.9 on 2021-12-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_auto_20211216_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='se',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='tim',
            new_name='time',
        ),
    ]
